mutation CreateUser($input: CreateUserInput!) {
  createUser(input: $input) {
    id
    username
    name
  }
}
mutation EditUser($input: EditUserInput!) {
  editUser(input: $input) {
    id
    username
    name
  }
}
mutation DeleteUser($username: String!) {
  deleteUser(username: $username) {
    id
    username
    name
  }
}
query GetUser($username: String!) {
  getUser(username: $username) {
    id
    username
    name
  }
}
query GetAllUsers($nextToken: String) {
  getAllUsers(nextToken: $nextToken) {
    items {
      id
      username
      name
    }
  }
}
